dataset_dir: ./datasets
dataset_name: t2m
save_dir: outputs/eval_guided/humanml3d
generator_checkpoint: pretrained/coamd/best_fid.tar
ae_checkpoint: pretrained/ae/latest.tar
reward_model_path: pretrained/mar/top1_best.tar
model: CoAMD-SiT-XL
cuda: 0
guidance_lambda: 0.0
time_steps: 12
cfg: 4.5
temperature: 1.0
cal_mm: false
hard_pseudo_reorder: false
coamd_depth: 6
repeat_time: 20
num_workers: 4
seed: 0
