dataset_dir: ./datasets
dataset_name: t2m
save_dir: outputs/train_coamd/humanml3d
ae_checkpoint: pretrained/ae/latest.tar
model: CoAMD-SiT-XL
cuda: 0
batch_size: 64
epoch: 500
warm_up_iter: 2000
lr: 0.0002
milestones: [50000]
lr_decay: 0.1
diffmlps_batch_mul: 4
need_evaluation: true
seed: 0
num_workers: 4
log_every: 50
eval_every_epoch: 10
eval_start_epoch: 400
